// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1sDusiYeyNtuz_rLMDSGAWZOWmdgQBgE',
    appId: '1:712246897546:web:d49da9d118c79693a9f673',
    messagingSenderId: '712246897546',
    projectId: 'scholar-chat-7f1d6',
    authDomain: 'scholar-chat-7f1d6.firebaseapp.com',
    storageBucket: 'scholar-chat-7f1d6.firebasestorage.app',
    measurementId: 'G-WCEJ2Q00SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAaOdZwZ4OVBBfdxOh66Omvc-01md7G_I',
    appId: '1:712246897546:android:ae82f96dec8a7c6ba9f673',
    messagingSenderId: '712246897546',
    projectId: 'scholar-chat-7f1d6',
    storageBucket: 'scholar-chat-7f1d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK2lmlwaV-KYsFRLmEsn2YfIACxMxA_4I',
    appId: '1:712246897546:ios:f3527d566ca2bf35a9f673',
    messagingSenderId: '712246897546',
    projectId: 'scholar-chat-7f1d6',
    storageBucket: 'scholar-chat-7f1d6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
